# 전처리

### 1.레이블 인코딩

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [5]:
# 레이블 인코더 객체 생성
encoder = LabelEncoder()

In [6]:
# 데이터를 주어서 간을 봄,  일종의 학습
encoder.fit(items)

LabelEncoder()

In [7]:
# 인코딩 변환값 반환
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [8]:
# 실전에서는 
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [9]:
# 고수들은
labels = LabelEncoder().fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

### 2.One-hot encoding

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
labels = LabelEncoder().fit_transform(items)

In [13]:
type(labels)

numpy.ndarray

In [14]:
# 객체 생성,학습 후 변환
oh_encoder = OneHotEncoder()
labels = labels.reshape(-1,1)
oh_encoder.fit(labels)
one_hot = oh_encoder.transform(labels)
one_hot

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [16]:
print(one_hot.toarray())

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [17]:
# 실전에서는
labels = LabelEncoder().fit_transform(items)
oh_encoder = OneHotEncoder()
one_hot = oh_encoder.fit_transform(labels.reshape(-1,1))
one_hot.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

### 3.StandardScaler

In [19]:
from sklearn.datasets import load_iris
iris = load_iris()

In [20]:
from sklearn.preprocessing import StandardScaler
Scalar = StandardScaler()
iris_std = Scalar.fit_transform(iris.data)

In [21]:
import numpy as np
import pandas as pd

In [22]:
df = pd.DataFrame(iris_std, columns=iris.feature_names)
df['species'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0          -0.900681          1.019004          -1.340227         -1.315444   
1          -1.143017         -0.131979          -1.340227         -1.315444   
2          -1.385353          0.328414          -1.397064         -1.315444   
3          -1.506521          0.098217          -1.283389         -1.315444   
4          -1.021849          1.249201          -1.340227         -1.315444   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [23]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.500000e+02      1.500000e+02       1.500000e+02   
mean       -1.690315e-15     -1.842970e-15      -1.698641e-15   
std         1.003350e+00      1.003350e+00       1.003350e+00   
min        -1.870024e+00     -2.433947e+00      -1.567576e+00   
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00   
50%        -5.250608e-02     -1.319795e-01       3.364776e-01   
75%         6.745011e-01      5.586108e-01       7.627583e-01   
max         2.492019e+00      3.090775e+00       1.785832e+00   

       petal width (cm)     species  
count      1.500000e+02  150.000000  
mean      -1.409243e-15    1.000000  
std        1.003350e+00    0.819232  
min       -1.447076e+00    0.000000  
25%       -1.183812e+00    0.000000  
50%        1.325097e-01    1.000000  
75%        7.906707e-01    2.000000  
max        1.712096e+00    2.000000

### 4. MinMaxScaler

In [25]:
from sklearn.preprocessing import MinMaxScaler
mm_scaler = MinMaxScaler()
iris_scaler = mm_scaler.fit_transform(iris.data)

In [26]:
df2 = pd.DataFrame(iris_scaler, columns= iris.feature_names)
df2.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.222222          0.625000           0.067797          0.041667
1           0.166667          0.416667           0.067797          0.041667
2           0.111111          0.500000           0.050847          0.041667
3           0.083333          0.458333           0.084746          0.041667
4           0.194444          0.666667           0.067797          0.041667

In [27]:
df2.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            0.428704          0.440556           0.467458   
std             0.230018          0.181611           0.299203   
min             0.000000          0.000000           0.000000   
25%             0.222222          0.333333           0.101695   
50%             0.416667          0.416667           0.567797   
75%             0.583333          0.541667           0.694915   
max             1.000000          1.000000           1.000000   

       petal width (cm)  
count        150.000000  
mean           0.458056  
std            0.317599  
min            0.000000  
25%            0.083333  
50%            0.500000  
75%            0.708333  
max            1.000000