# Bag of Words

### 1. CountVectorizer

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['you konw i want your love. because i love you.']

In [4]:
count_vect = CountVectorizer()
output = count_vect.fit_transform(corpus)
output.toarray()

array([[1, 1, 2, 1, 2, 1]], dtype=int64)

In [5]:
count_vect.vocabulary_

{'you': 4, 'konw': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}

- 불용어를 제거한 BoW

In [9]:
# 자체 제거
text = ['Family is not an important thing. It`s everything.']
cvect = CountVectorizer(stop_words=['the','a','an','is'])
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1]]
{'family': 1, 'not': 4, 'important': 2, 'thing': 5, 'it': 3, 'everything': 0}


In [10]:
# Scikit-Learn 에서 제공하는 불용어 사용
text = ['Family is not an important thing. It`s everything.']
cvect = CountVectorizer(stop_words='english')
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}


In [11]:
#NLTK에서 제공하는 불용어 사용
from nltk.corpus import stopwords
sw = stopwords.words('english')
len(sw)

179

In [12]:
text = ['Family is not an important thing. It`s everything.']
cvect = CountVectorizer(stop_words=sw)
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


In [1]:
def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key

- M-gram

In [16]:
text = ['Machine learning is fun and not boring.']
cvect = CountVectorizer()
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1]]
{'machine': 5, 'learning': 4, 'is': 3, 'fun': 2, 'and': 0, 'not': 6, 'boring': 1}


In [17]:
cvect = CountVectorizer(ngram_range=(1,2))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1 1 1 1 1 1 1]]
{'machine': 9, 'learning': 7, 'is': 5, 'fun': 3, 'and': 0, 'not': 11, 'boring': 2, 'machine learning': 10, 'learning is': 8, 'is fun': 6, 'fun and': 4, 'and not': 1, 'not boring': 12}


In [18]:
cvect = CountVectorizer(ngram_range=(1,3), stop_words='english')
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1 1 1]]
{'machine': 6, 'learning': 3, 'fun': 1, 'boring': 0, 'machine learning': 7, 'learning fun': 4, 'fun boring': 2, 'machine learning fun': 8, 'learning fun boring': 5}


In [19]:
cvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': 'english',
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

### 2. TF-IDF Vectorizer

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'you know I want your love',
    'I like you.',
    'What should I do'
]

In [23]:
cvect = CountVectorizer()
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [25]:
tvect = TfidfVectorizer()
print(tvect.fit_transform(corpus).toarray())
print(tvect.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}
